# API key from Jellyfin server
export APIKEY=YOUR-API-KEY-HERE

# Jellyfin server address
export SERVER=http://example.com

# minimum idle time required for server to be considered inactive
# in seconds
export IDLETIME=300
